apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        resources:
          requests:
            cpu: "1000m"
            memory: "1700Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: rootpassword
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        # MOUNTING THE VOLUME HERE
        volumeMounts:
        - name: efs-storage
          mountPath: /var/lib/mysql
          subPath: mysql
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-claim
