apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::831869585626:role/eksctl-demo-cluster-cluster-FargatePodExecutionRole-eXtFMME2bHJt
      groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      username: system:node:{{SessionName}}
  mapUsers: |
    - userarn: arn:aws:iam::831869585626:user/abhinav
      username: abhinav
      groups:
        - system:masters
    - userarn: arn:aws:iam::831869585626:user/eks
      username: eks
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2025-11-08T11:28:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "32541"
  uid: df4bf5d5-885a-496e-8c8a-0067d7ffa929
