apiVersion: v1
kind: Pod
metadata:
  name: cpu-hog
spec:
  restartPolicy: Never
  containers:
    - name: stress
      image: polinux/stress
      command: ["stress"]
      args: ["--cpu", "1", "--timeout", "30"]
      resources:
        requests:
          cpu: 50m
        limits:
          cpu: 50m
